In [ ]:
'''Q.1 Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?'''

**NumPy (Numerical Python**) is a core library for scientific computing and data analysis in Python. It provides support for working with large, multi-dimensional arrays and includes a collection of mathematical functions to perform efficient operations on these arrays.

Purpose of NumPy:

1.Efficient numerical computation using array-based operations.

2.Foundation for other libraries like pandas, SciPy, and scikit-learn.

3.Supports complex operations such as linear algebra, Fourier transforms, and random number generation.

4.Improves performance and memory usage for large datasets.

Advantages of NumPy:

1.Speed and Performance:

Operations are implemented in C, making them faster than Python lists.

Supports vectorized operations (no explicit loops).

2.Memory Efficiency:

Arrays use less memory compared to lists.

Stores data in contiguous memory blocks.

3.Broadcasting:

Allows arithmetic operations on arrays of different shapes without writing loops.

4.Rich Functionality:

Built-in functions for mathematical, statistical, and linear algebra operations.

5.Interoperability:

Easily integrates with other scientific libraries and tools.

Enhancement over Python:

1. Python Lists:

Speed: Slower

Memory: Efficiency	Less efficient

Operations:	Manual looping

Functionality: Limited math support

2. NumPy Arrays:

Speed:	Faster (C-based backend)

Memory Efficiency:	More efficient

Operations:	Vectorized operations

Functionality:	Extensive math functions

Conclusion:

NumPy enhances Python by providing high-speed, memory-efficient tools for numerical and scientific computing, making it essential for data analysis and research applications

In [1]:
# Python list
a = [1, 2, 3]
b = [4, 5, 6]
c = [a[i] + b[i] for i in range(len(a))]

# NumPy array
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b

In [ ]:
'''Q.2 Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?'''

In NumPy, both np.mean() and np.average() are used to calculate the mean (average) of array elements, but there are key differences in their functionality and use cases.

**np.mean()**

Purpose:

Computes the arithmetic mean (unweighted) of array elements along a specified axis.

Syntax:

np.mean(a, axis=None, dtype=None, out=None, keepdims=False)

Key Features:

1.Always computes the simple (unweighted) mean.

2.Commonly used for general-purpose average calculations.

In [2]:
import numpy as np
a = np.array([1, 2, 3, 4])
np.mean(a)  # Output: 2.5

np.float64(2.5)

**np.average()**

Purpose:

Computes the weighted average of array elements. If no weights are given, behaves like np.mean().

Syntax:

np.average(a, axis=None, weights=None, returned=False)

Key Features:

1.Can compute weighted mean using the weights parameter.

2.returned=True will return a tuple of the average and the sum of weights.

In [3]:
a = np.array([1, 2, 3, 4])
weights = np.array([1, 1, 0, 0])
np.average(a, weights=weights)  # Output: 1.5


np.float64(1.5)

When to Use Each

1.Use np.mean() when:

You need a simple, unweighted average.

You want cleaner, more readable code for standard use.

2.Use np.average() when:

You need a weighted average.

You want to give more importance to certain values in the array.

You want the sum of weights returned (with returned=True).

Conclusion:

1.np.mean() is simpler and more common for general use.

2.np.average() is more flexible when dealing with weights or importance of elements.

In [ ]:
'''Q.3 Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.'''

1D Array Reversal:

A 1D array is reversed simply by slicing with a step of -1.

In [4]:
#Method: Slicing
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5])
reversed_1d = arr_1d[::-1]
print(reversed_1d)  # Output: [5 4 3 2 1]

[5 4 3 2 1]


2D Array Reversal:

For 2D arrays, you can reverse:

1.Rows (axis=0)

2.Columns (axis=1)

3.Entire array (both axes)

In [5]:
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [6]:
# Method 1: Reverse Rows (axis=0)
reversed_rows = arr_2d[::-1, :]
print(reversed_rows)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [7]:
#Method 2: Reverse Columns (axis=1)
reversed_cols = arr_2d[:, ::-1]
print(reversed_cols)


[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [8]:
#Method 3: Reverse Both Axes (complete flip)
reversed_both = arr_2d[::-1, ::-1]
print(reversed_both)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [9]:
#Method 4: Using np.flip()
# Flip entire array (all axes)
np.flip(arr_2d)

# Flip along axis=0 (rows)
np.flip(arr_2d, axis=0)

# Flip along axis=1 (columns)
np.flip(arr_2d, axis=1)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

Summary:

1. Task: Reverse 1D

Method: array	arr[::-1]

2. Task:Reverse 2D rows

Method: arr[::-1, :] or np.flip(arr, axis=0)

3. Task:Reverse 2D columns

Method: arr[:, ::-1] or np.flip(arr, axis=1)

4. Task:Reverse both axes

Method: arr[::-1, ::-1] or np.flip(arr)

In [ ]:
'''Q.4  How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.'''

You can use the .dtype attribute to find out the data type of elements in a NumPy array.

In [10]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr.dtype)  # Output: int64 (or int32, depending on the system)


int64


Other Useful Functions:

1. arr.astype(dtype) → Converts the array to a new data type.

2. np.result_type(obj1, obj2) → Determines the result type from operations on two arrays.

3. np.can_cast(from_dtype, to_dtype) → Checks if safe casting is possible.

Importance of Data Types:

1. Memory Management:

Each data type occupies a fixed number of bytes.

Choosing the correct type reduces memory usage, especially for large datasets.

Example: int8 uses 1 byte, while int64 uses 8 bytes.

2. Performance:

Simpler or smaller data types (like int32, float32) are faster to process.

They improve computation speed and make better use of CPU cache.

Reduces data loading and processing time.

3. Accuracy and Precision:

Using appropriate data types (e.g., float64 for precision) ensures accurate results in scientific or financial calculations.

4. Compatibility:

Consistent data types prevent unexpected behavior during mathematical operations.

Conclusion:

Understanding and selecting the correct data type in NumPy is crucial for efficient memory usage, faster performance, and accurate computation.

In [ ]:
'''Q.5 Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?'''

Definition:

In NumPy, an ndarray (n-dimensional array) is a powerful object used to store elements of the same data type in a multi-dimensional, fixed-size grid.

Key Features of ndarrays:

1. Homogeneous Elements:
All elements have the same data type (e.g., int, float).

2. Multi-dimensional Support:
Can create 1D, 2D, 3D, or higher-dimensional arrays.

3. Efficient Memory Usage:
Uses less memory than Python lists due to fixed-type storage.

4. Vectorized Operations:
Supports fast element-wise operations without using loops.

5. Built-in Mathematical Functions:
Offers optimized functions like sum(), mean(), reshape(), etc.

Differences from Python Lists:

**ndarray**

Data Type: Homogeneous (same type)

Performance	Faster: (C-based operations)

Memory Efficiency: More efficient (fixed type)

Functionality:	Supports broadcasting, slicing

Dimensions:	Multi-dimensional supported

**Python List**

Data Type: Heterogeneous (mixed types)

Performance: Slower (Python loops)

Memory Efficiency: Less efficient (dynamic types)

Functionality: Limited math functionality

Dimensions: Typically 1D or nested

Conclusion:

NumPy ndarrays are more efficient, faster, and feature-rich compared to standard Python lists, making them ideal for numerical and scientific computing.

In [ ]:
'''Q.6 Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.'''

NumPy arrays offer several performance advantages over Python lists in large-scale numerical operations:

1. Faster Computation:

NumPy is implemented in C, enabling fast, low-level operations.

Supports vectorized operations, eliminating the need for slow Python loops.

2. Lower Memory Usage:

NumPy arrays store elements of fixed data types, reducing memory consumption.

Python lists store references to objects, which uses more memory.

3. Efficient Broadcasting:

NumPy supports broadcasting, allowing operations on arrays of different shapes without explicit looping.

4. Built-in Optimized Functions:

NumPy provides optimized mathematical and statistical functions (e.g., mean(), sum(), dot()) that are much faster than writing custom code with lists.

In [11]:
#Example (Speed Comparison):
import numpy as np
import time

a = list(range(1000000))
b = np.array(a)

# Using Python list
start = time.time()
c = [x * 2 for x in a]
print("List time:", time.time() - start)

# Using NumPy array
start = time.time()
d = b * 2
print("NumPy time:", time.time() - start)


List time: 0.05088233947753906
NumPy time: 0.0033597946166992188


Conclusion:

For large-scale numerical tasks, NumPy arrays are preferred due to their speed, memory efficiency, and optimized operations, making them ideal for data science and scientific computing.

In [ ]:
'''Q.7 Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.'''

In NumPy, vstack() and hstack() are used to stack arrays vertically or horizontally.

1. np.vstack() – Vertical Stack:

Stacks arrays row-wise (one on top of another).

Arrays must have the same number of columns.

In [12]:
import numpy as np
a = np.array([1, 2])
b = np.array([3, 4])
result = np.vstack((a, b))
print(result)


[[1 2]
 [3 4]]


2. np.hstack() – Horizontal Stack:

Stacks arrays column-wise (side by side).

Arrays must have the same number of rows.

In [13]:
a = np.array([1, 2])
b = np.array([3, 4])
result = np.hstack((a, b))
print(result)


[1 2 3 4]


| Function   | Direction         | Condition                  | Example Output Shape |
| ---------- | ----------------- | -------------------------- | -------------------- |
| `vstack()` | Vertical (rows)   | Same number of columns | (2, N)               |
| `hstack()` | Horizontal (cols) | Same number of rows    | (N,) or (1, N+M)     |

Conclusion:

1.Use vstack() to stack arrays vertically (row-wise).

2.Use hstack() to stack arrays horizontally (column-wise).

These functions are useful in data combination and reshaping operations.

In [ ]:
'''Q.8 Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.'''

In NumPy, fliplr() and flipud() are used to flip (reverse) arrays along specific axes.

1. np.fliplr() – Flip Left to Right (Columns):

-Flips the array horizontally.

-Works only on 2D or higher arrays.

-Reverses the order of columns (left ↔ right).

In [14]:
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(np.fliplr(a))


[[3 2 1]
 [6 5 4]]


2. np.flipud() – Flip Up to Down (Rows):

-Flips the array vertically.

-Works on any-dimensional array.

-Reverses the order of rows (top ↔ bottom).

In [15]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(np.flipud(a))


[[4 5 6]
 [1 2 3]]


| Function   | Flips Along         | Affects                | Works On            |
| ---------- | ------------------- | ---------------------- | ------------------- |
| `fliplr()` | Horizontal (axis=1) | Columns (left ↔ right) | 2D or higher arrays |
| `flipud()` | Vertical (axis=0)   | Rows (top ↔ bottom)    | Any-dimensional     |

Conclusion:

1.Use fliplr() to flip arrays horizontally.

2.Use flipud() to flip arrays vertically.

3.These functions are useful for image processing, matrix operations, and data transformations.

In [ ]:
'''Q.9 Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?'''

Definition:

The np.array_split() method in NumPy is used to split an array into multiple sub-arrays.

Functionality:

Syntax:

np.array_split(array, number_of_splits, axis=0)

It splits the array along the specified axis (default is axis=0).

Handling Uneven Splits:

If the array cannot be divided equally, array_split() distributes the extra elements to the earlier sub-arrays.

It ensures that all data is included, even when sizes are not perfectly divisible.

In [17]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
result = np.array_split(a, 3)
print(result)


[array([1, 2]), array([3, 4]), array([5])]


Conclusion:

1.array_split() is useful for flexible splitting, especially when the array length is not divisible by the number of splits.

2.It ensures no data loss by balancing the split as evenly as possible.

In [ ]:
'''Q.10 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?'''

1. Vectorization:

Vectorization means performing operations on entire arrays without using explicit loops.

NumPy uses low-level C-based implementations to perform these operations efficiently.

In [18]:
import numpy as np
a = np.array([1, 2, 3])
b = a * 2  # Vectorized operation


Benefits:

-Faster execution

-Cleaner, more readable code

-Better CPU utilization

2. Broadcasting:

Broadcasting allows NumPy to perform operations on arrays of different shapes by automatically expanding the smaller array to match the larger one.

In [19]:
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])
result = a + b  # b is broadcasted to match shape of a


Rules:

Dimensions are compared from right to left.

Dimensions are compatible when they are equal or one of them is 1.

| Feature           | Contribution to Efficiency                                   |
| ----------------- | ------------------------------------------------------------ |
| **Vectorization** | Reduces use of Python loops, speeds up computation           |
| **Broadcasting**  | Enables operations on mismatched shapes without copying data |

Conclusion:

Vectorization and broadcasting are core NumPy concepts that make array operations faster, more memory-efficient, and simpler in syntax, especially in large-scale numerical computing.



In [ ]:
#PRACTICAL

In [ ]:
'''Q.1 Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns'''

In [ ]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(arr)

# Interchange rows and columns (transpose)
transposed_arr = arr.T
print("\nTransposed Array:")
print(transposed_arr)


Explanation:

np.random.randint(1, 101, size=(3, 3)) generates a 3x3 array with random integers from 1 to 100.

T is used to transpose the array — it swaps rows with columns.

In [ ]:
'''Q.2 Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.'''

In [ ]:
import numpy as np

# Step 1: Generate a 1D NumPy array with 10 elements
arr = np.arange(1, 11)
print("Original 1D Array:")
print(arr)

# Step 2: Reshape it into a 2x5 array
arr_2x5 = arr.reshape(2, 5)
print("\nReshaped to 2x5 Array:")
print(arr_2x5)

# Step 3: Reshape it into a 5x2 array
arr_5x2 = arr.reshape(5, 2)
print("\nReshaped to 5x2 Array:")
print(arr_5x2)


Explanation:

np.arange(1, 11) creates a 1D array of 10 elements from 1 to 10.

reshape(rows, columns) changes the shape without changing data.

Total elements (10) remain constant across reshaping.

In [ ]:
'''Q.3 Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.'''

In [ ]:
import numpy as np

# Step 1: Create a 4x4 array with random float values
arr = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(arr)

# Step 2: Add a border of zeros around it to make a 6x6 array
arr_with_border = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Zero Border:")
print(arr_with_border)


Explanation:

np.random.rand(4, 4) creates a 4x4 array of random floats in [0.0, 1.0).

np.pad() is used to add padding:

pad_width=1 adds 1 row/column of zeros on all sides.

mode='constant', constant_values=0 ensures zeros are added.

In [ ]:
'''Q.4 Using NumPy, create an array of integers from 10 to 60 with a step of 5.'''

In [ ]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
arr = np.arange(10, 61, 5)
print("Array from 10 to 60 with step 5:")
print(arr)


Explanation:

np.arange(start, stop, step) generates values from start to stop - 1 (not inclusive of stop).

So np.arange(10, 61, 5) gives:
[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60]

In [ ]:
'''Q.5 Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element'''

In [ ]:
import numpy as np

# Step 1: Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Step 2: Apply case transformations
upper_arr = np.char.upper(arr)
lower_arr = np.char.lower(arr)
title_arr = np.char.title(arr)
capitalize_arr = np.char.capitalize(arr)

# Display results
print("Original Array:", arr)
print("Uppercase:", upper_arr)
print("Lowercase:", lower_arr)
print("Title Case:", title_arr)
print("Capitalized:", capitalize_arr)


Explanation:

np.char.upper() – converts all characters to uppercase.

np.char.lower() – converts all characters to lowercase.

np.char.title() – capitalizes the first letter of each word.

np.char.capitalize() – capitalizes the first letter of the string, lowers the rest.

In [ ]:
'''Q.6 Generate a NumPy array of words. Insert a space between each character of every word in the array'''

In [ ]:
import numpy as np

# Step 1: Create a NumPy array of words
arr = np.array(['python', 'numpy', 'pandas'])

# Step 2: Insert a space between each character of every word
spaced_arr = np.char.join(' ', arr)

# Display the result
print("Original Array:", arr)
print("Spaced Words:", spaced_arr)


Explanation:

np.char.join(sep, arr) adds the specified separator (' ') between each character of each string in the array.

It works element-wise and is ideal for vectorized string manipulation.

In [ ]:
'''Q.7 Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.'''

In [ ]:
import numpy as np

# Step 1: Create two 2D NumPy arrays
arr1 = np.array([[10, 20], [30, 40]])
arr2 = np.array([[2, 4], [5, 8]])

# Step 2: Perform element-wise operations
addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

# Display results
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Explanation:

Element-wise operations mean that each corresponding element of the arrays is operated on.

Arrays must be of the same shape for direct element-wise operations.

NumPy uses vectorized operations which are faster and more efficient than loops.

In [ ]:
'''Q.8 Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.'''

In [ ]:
import numpy as np

# Step 1: Create a 5x5 identity matrix
identity_matrix = np.identity(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Step 2: Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


Explanation:

np.identity(n) creates an n x n identity matrix, with 1s on the main diagonal and 0s elsewhere.

np.diag(array) extracts the diagonal from a matrix or creates a diagonal matrix from a 1D array.

In [ ]:
'''Q.9 Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.'''

In [ ]:
import numpy as np

# Step 1: Generate a NumPy array of 100 random integers between 0 and 1000
arr = np.random.randint(0, 1001, size=100)
print("Original Array:\n", arr)

# Step 2: Define a function to check for prime numbers
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            return False
    return True

# Step 3: Vectorize the function and apply it to the array
prime_check = np.vectorize(is_prime)
prime_numbers = arr[prime_check(arr)]

# Display prime numbers
print("\nPrime Numbers in the Array:\n", prime_numbers)


Explanation:

np.random.randint(0, 1001, size=100) generates 100 integers from 0 to 1000.

is_prime() checks if a number is prime using trial division.

np.vectorize() allows the function to work element-wise on arrays.

Final result filters only prime numbers from the original array.

In [ ]:
'''Q.10  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.'''

In [ ]:
import numpy as np

# Step 1: Create a NumPy array of daily temperatures for 30 days
temperatures = np.random.randint(20, 41, size=30)  # temperatures between 20°C and 40°C
print("Daily Temperatures for the Month:")
print(temperatures)

# Step 2: Reshape into 5 weeks (5x7) assuming 30 days ~ 4 weeks + 2 days (we take 28 for 4 full weeks)
weeks = temperatures[:28].reshape(4, 7)

# Step 3: Calculate weekly averages
weekly_avg = weeks.mean(axis=1)

# Display weekly averages
print("\nWeekly Average Temperatures:")
for i, avg in enumerate(weekly_avg, start=1):
    print(f"Week {i}: {avg:.2f}°C")

# Optionally handle remaining 2 days
if len(temperatures) > 28:
    extra_avg = temperatures[28:].mean()
    print(f"\nRemaining {len(temperatures) - 28} Days Average: {extra_avg:.2f}°C")


Explanation:

Use np.random.randint() to simulate daily temperature data.

Use .reshape(4, 7) to organize into weekly blocks (assuming 28 days for simplicity).

Use .mean(axis=1) to get average per row (i.e., per week).